---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - python
  pep8:
    enabled: true
  shellcheck:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: false
  radon:
    enabled: true
ratings:
  paths:
    - "bin/*"
    - "**.js"
    - "**.py"
exclude_paths:
  - .cache/
  - __pycache__/
  - \*.egg-info/
  - config/
  - doc/
  - tmp/
  - lib/
  - static/
  - vendor/
  - venv*/
  - node_modules/
  - .*rc
  - .env*
  - \*.md
  - \*.txt
  - \*.json
