# https://docs.gitlab.com/ce/ci/yaml/
stages:
  - compile-catalog

variables:
  APT_CACHE_DIR: apt-cache

cache:
  untracked: true
  paths:
    - apt-cache

compile:
  stage: compile-catalog
  image: debian:latest
  before_script:
    - mkdir -pv $APT_CACHE && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE" install -y
      gettext make
  script:
    - make catalog
  except:
    - tags
