# https://docs.gitlab.com/ce/ci/yaml/
stages:
  - check-style
  - compile-catalog
  - build-assets
  - test-code

check:
  stage: check-style
  image: python:3.5
  services:
  variables:
    ENV: development
  before_script:
    - python --version
    - pip --version
    - pip install flake8 flake8-docstrings -c constraints.txt
  script:
    - make clean
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

compile:
  stage: compile-catalog
  image: python:3.5
  services:
  variables:
    ENV: development
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y --no-install-recommends gcc zlib1g zlib1g-dev
    - apt-get -qq install -y --no-install-recommends
      libmemcached11 libmemcached-dev
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make clean
    - make setup
    - make catalog
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

build:
  stage: build-assets
  image: node:7.10.1
  services:
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --ignore-scripts
  script:
    - make clean
    - gulp
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

test:
  stage: test-code
  image: python:3.5
  services:
    - postgres:9.6
    - redis:3.2
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
    POSTGRES_DB: aarau_test
    POSTGRES_USER: aarau
    POSTGRES_PASSWORD: aarau
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make clean
    - make setup
    - make db-init
    - make db-migrate
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags
