# https://docs.gitlab.com/ce/ci/yaml/
stages:
  - check-style
  - setup-deps
  - compile-catalog
  - build-assets
  - test-code

variables:
  APT_CACHE_DIR: apt-cache
  PIP_CACHE_DIR: pip-cache

cache:
  untracked: true
  paths:
    - apt-cache
    - pip-cache
    - node_modules

check:
  stage: check-style
  image: python:3.5
  services:
  variables:
    ENV: development
  before_script:
    - python --version
    - pip --version
    - pip install flake8 flake8-docstrings -c constraints.txt
  script:
    - make clean
    - make check
  except:
    - tags

setup:
  stage: setup-deps
  image: python:3.5
  services:
  variables:
    ENV: production
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      gettext make
      gcc zlib1g zlib1g-dev libmemcached11 libmemcached-dev
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make clean
    - make setup
  except:
    - tags

compile:
  stage: compile-catalog
  image: python:3.5
  services:
  variables:
    ENV: production
  before_script:
    - python --version
    - pip --version
  script:
    - make clean
    - make catalog
  except:
    - tags

build:
  stage: build-assets
  image: node:7.10.1
  services:
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --ignore-scripts
  script:
    - make clean
    - gulp
  except:
    - tags

test:
  stage: test-code
  image: python:3.5
  services:
    - postgres:9.6
    - redis:3.2
  variables:
    ENV: test
    POSTGRES_DB: aarau_test
    POSTGRES_USER: aarau
    POSTGRES_PASSWORD: aarau
  before_script:
    - python --version
    - pip --version
  script:
    - make clean
    - make db-init
    - make db-migrate
    - make coverage
  except:
    - tags
