---
reserved_words:
  common:
    - scrolliris
    - scroll-iris
    - scroll_iris
    - lupinesoftware
    - lupine-software
    - lupine_software
    - lupinesoftwarellc
    - lupinesoftware-llc
    - lupinesoftware_llc
    - lupine-software-llc
    - lupine-software_llc
    - lupine_software_llc
    - lupine_software-llc
  project:
    namespace: []
  site:
    slug: []
  user:
    username: []
